### ISSUE TITLE
Ctrl+C causes an exception in the REPL when running on .NET Core

### ISSUE THREAD

**Issue by leppie** [IronScheme/IronScheme#117]
```
Unhandled Exception: System.PlatformNotSupportedException: Thread abort is not supported on this platform.
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Console.HandleBreakEvent(ConsoleSpecialKey controlKey)
   at System.ConsolePal.ControlCHandlerRegistrar.BreakEvent(Int32 controlType)
```

Seems to affect all .NET Core versions.

**Comment by leppie** [comment]
`Thread.Abort` has been removed from .NET Core. 

Currently I have no idea how to implement this in another way that would not take a tremendous amount of efforts and hacks.

Best I can do is maybe prompt whether to kill the REPL or not. Or show a warning.

**Comment by leppie** [comment]
https://github.com/dotnet/runtime/pull/71661
